// Generated by tools/contracts/generator.mjs. Do not edit.
import { Type, type Static } from "@sinclair/typebox";
import { Value } from "@sinclair/typebox/value";

export const AccountProfileProjectionSchema = Type.Object(
  {
    authority: Type.Array(Type.String(), { maxItems: 0 }),
    displayName: Type.String({ maxLength: 128, minLength: 1 }),
    id: Type.String({ maxLength: 128, minLength: 1 }),
    verifiedEmail: Type.String({ maxLength: 320, minLength: 3 }),
    version: Type.Integer({ minimum: 1 }),
  },
  { $id: "AccountProfileProjection.v1", additionalProperties: false },
);
export type AccountProfileProjection = Static<
  typeof AccountProfileProjectionSchema
>;

export const AccountProfileRequestSchema = Type.Object(
  { audience: Type.Literal("self") },
  { $id: "AccountProfileRequest.v1", additionalProperties: false },
);
export type AccountProfileRequest = Static<typeof AccountProfileRequestSchema>;

export const AccountSecurityHistoryListSchema = Type.Object(
  {
    history: Type.Array(
      Type.Object(
        {
          approximateLocation: Type.Optional(
            Type.String({ maxLength: 256, minLength: 1 }),
          ),
          device: Type.Optional(Type.String({ maxLength: 256, minLength: 1 })),
          id: Type.String({ maxLength: 128, minLength: 1 }),
          kind: Type.Union([
            Type.Literal("accepted_sign_in"),
            Type.Literal("clerk_reverification"),
            Type.Literal("account_suspension"),
          ]),
          occurredAt: Type.String({ maxLength: 35, minLength: 20 }),
          suspensionStatus: Type.Optional(
            Type.Union([
              Type.Literal("imposed"),
              Type.Literal("reinstated"),
              Type.Literal("expired"),
            ]),
          ),
        },
        { additionalProperties: false },
      ),
    ),
  },
  { $id: "AccountSecurityHistoryList.v1", additionalProperties: false },
);
export type AccountSecurityHistoryList = Static<
  typeof AccountSecurityHistoryListSchema
>;

export const AccountSecurityHistoryRequestSchema = Type.Object(
  { audience: Type.Literal("self") },
  { $id: "AccountSecurityHistoryRequest.v1", additionalProperties: false },
);
export type AccountSecurityHistoryRequest = Static<
  typeof AccountSecurityHistoryRequestSchema
>;

export const ChangeDisplayNameRequestSchema = Type.Object(
  {
    displayName: Type.String({ maxLength: 128, minLength: 1 }),
    expectedVersion: Type.Integer({ minimum: 1 }),
    idempotencyKey: Type.String({ maxLength: 128, minLength: 1 }),
  },
  { $id: "ChangeDisplayNameRequest.v1", additionalProperties: false },
);
export type ChangeDisplayNameRequest = Static<
  typeof ChangeDisplayNameRequestSchema
>;

export const CreateDocketSessionRequestSchema = Type.Object(
  { idempotencyKey: Type.String({ maxLength: 128, minLength: 1 }) },
  { $id: "CreateDocketSessionRequest.v1", additionalProperties: false },
);
export type CreateDocketSessionRequest = Static<
  typeof CreateDocketSessionRequestSchema
>;

export const DocketSessionListSchema = Type.Object(
  {
    sessions: Type.Array(
      Type.Object(
        {
          approximateLocation: Type.String({ maxLength: 256, minLength: 1 }),
          createdAt: Type.String({ maxLength: 35, minLength: 20 }),
          device: Type.String({ maxLength: 256, minLength: 1 }),
          expiresAt: Type.String({ maxLength: 35, minLength: 20 }),
          id: Type.String({ maxLength: 128, minLength: 1 }),
          inactivityExpiresAt: Type.String({ maxLength: 35, minLength: 20 }),
          lastActivityAt: Type.String({ maxLength: 35, minLength: 20 }),
          privilegedActivatedAt: Type.Optional(
            Type.String({ maxLength: 35, minLength: 20 }),
          ),
          sessionClass: Type.Union([
            Type.Literal("ordinary"),
            Type.Literal("privileged"),
          ]),
          status: Type.Union([
            Type.Literal("active"),
            Type.Literal("expired"),
            Type.Literal("revoked"),
          ]),
          version: Type.Integer({ minimum: 1 }),
        },
        { additionalProperties: false },
      ),
    ),
  },
  { $id: "DocketSessionList.v1", additionalProperties: false },
);
export type DocketSessionList = Static<typeof DocketSessionListSchema>;

export const DocketSessionResultSchema = Type.Object(
  {
    account: Type.Object(
      {
        authority: Type.Array(Type.String(), { maxItems: 0 }),
        displayName: Type.String({ maxLength: 128, minLength: 1 }),
        id: Type.String({ maxLength: 128, minLength: 1 }),
        verifiedEmail: Type.String({ maxLength: 320, minLength: 3 }),
        version: Type.Integer({ minimum: 1 }),
      },
      { $id: "AccountProfileProjection.v1", additionalProperties: false },
    ),
    session: Type.Object(
      {
        approximateLocation: Type.String({ maxLength: 256, minLength: 1 }),
        createdAt: Type.String({ maxLength: 35, minLength: 20 }),
        device: Type.String({ maxLength: 256, minLength: 1 }),
        expiresAt: Type.String({ maxLength: 35, minLength: 20 }),
        id: Type.String({ maxLength: 128, minLength: 1 }),
        inactivityExpiresAt: Type.String({ maxLength: 35, minLength: 20 }),
        lastActivityAt: Type.String({ maxLength: 35, minLength: 20 }),
        privilegedActivatedAt: Type.Optional(
          Type.String({ maxLength: 35, minLength: 20 }),
        ),
        sessionClass: Type.Union([
          Type.Literal("ordinary"),
          Type.Literal("privileged"),
        ]),
        status: Type.Union([
          Type.Literal("active"),
          Type.Literal("expired"),
          Type.Literal("revoked"),
        ]),
        version: Type.Integer({ minimum: 1 }),
      },
      { additionalProperties: false },
    ),
  },
  { $id: "DocketSessionResult.v1", additionalProperties: false },
);
export type DocketSessionResult = Static<typeof DocketSessionResultSchema>;

export const IdentitySessionProjectionSchema = Type.Object(
  {
    audience: Type.Literal("self"),
    authenticated: Type.Literal(true),
    userId: Type.String({ maxLength: 128, minLength: 1 }),
  },
  { $id: "IdentitySessionProjection.v1", additionalProperties: false },
);
export type IdentitySessionProjection = Static<
  typeof IdentitySessionProjectionSchema
>;

export const IdentitySessionRequestSchema = Type.Object(
  { audience: Type.Literal("self") },
  { $id: "IdentitySessionRequest.v1", additionalProperties: false },
);
export type IdentitySessionRequest = Static<
  typeof IdentitySessionRequestSchema
>;

export const ListDocketSessionsRequestSchema = Type.Object(
  { audience: Type.Literal("self") },
  { $id: "ListDocketSessionsRequest.v1", additionalProperties: false },
);
export type ListDocketSessionsRequest = Static<
  typeof ListDocketSessionsRequestSchema
>;

export const RevokeAllDocketSessionsRequestSchema = Type.Object(
  { idempotencyKey: Type.String({ maxLength: 128, minLength: 1 }) },
  { $id: "RevokeAllDocketSessionsRequest.v1", additionalProperties: false },
);
export type RevokeAllDocketSessionsRequest = Static<
  typeof RevokeAllDocketSessionsRequestSchema
>;

export const RevokeDocketSessionRequestSchema = Type.Object(
  {
    expectedVersion: Type.Integer({ minimum: 1 }),
    idempotencyKey: Type.String({ maxLength: 128, minLength: 1 }),
    sessionId: Type.String({ maxLength: 128, minLength: 1 }),
  },
  { $id: "RevokeDocketSessionRequest.v1", additionalProperties: false },
);
export type RevokeDocketSessionRequest = Static<
  typeof RevokeDocketSessionRequestSchema
>;

export const StableErrorEnvelopeSchema = Type.Object(
  {
    code: Type.Union([
      Type.Literal("AUTHENTICATION_REQUIRED"),
      Type.Literal("AUTHORITY_STALE"),
      Type.Literal("DISPLAY_NAME_CHANGE_TOO_SOON"),
      Type.Literal("REQUEST_INVALID"),
      Type.Literal("RESPONSE_INVALID"),
      Type.Literal("IDENTITY_INVALID"),
      Type.Literal("SESSION_EXPIRED"),
      Type.Literal("SESSION_LIMIT_REACHED"),
      Type.Literal("FIXED_IDENTITY_FORBIDDEN"),
    ]),
    fieldIssues: Type.Optional(
      Type.Array(
        Type.Object(
          { message: Type.String(), path: Type.String() },
          { additionalProperties: false },
        ),
      ),
    ),
    message: Type.String({ minLength: 1 }),
    requestId: Type.String({ maxLength: 128, minLength: 1 }),
  },
  { $id: "StableErrorEnvelope.v1", additionalProperties: false },
);
export type StableErrorEnvelope = Static<typeof StableErrorEnvelopeSchema>;

export interface ContractTransportResponse {
  readonly status: number;
  readonly body: unknown;
}
export type ContractTransport = (
  request: Readonly<{ method: string; path: string; body?: unknown }>,
) => Promise<ContractTransportResponse>;

export class ContractClientError extends Error {
  constructor(
    public readonly code: string,
    message: string,
    public readonly requestId?: string,
  ) {
    super(message);
    this.name = "ContractClientError";
  }
}

export function createDocketClient(transport: ContractTransport) {
  return {
    async getIdentitySession(
      input: unknown,
    ): Promise<IdentitySessionProjection> {
      if (!Value.Check(IdentitySessionRequestSchema, input)) {
        throw new ContractClientError(
          "REQUEST_INVALID",
          "The request is invalid.",
        );
      }
      const query = new URLSearchParams(input).toString();
      const response = await transport({
        method: "GET",
        path: "/v1/session" + (query ? `?${query}` : ""),
      });
      if (response.status === 200) {
        if (!Value.Check(IdentitySessionProjectionSchema, response.body)) {
          throw new ContractClientError(
            "RESPONSE_INVALID",
            "The response did not match its contract.",
          );
        }
        return response.body;
      }
      if (!Value.Check(StableErrorEnvelopeSchema, response.body)) {
        throw new ContractClientError(
          "RESPONSE_INVALID",
          "The error response did not match its contract.",
        );
      }
      const error = response.body;
      throw new ContractClientError(error.code, error.message, error.requestId);
    },

    async createDocketSession(input: unknown): Promise<DocketSessionResult> {
      if (!Value.Check(CreateDocketSessionRequestSchema, input)) {
        throw new ContractClientError(
          "REQUEST_INVALID",
          "The request is invalid.",
        );
      }
      const response = await transport({
        method: "POST",
        path: "/v1/docket-sessions",
        body: input,
      });
      if (response.status === 200) {
        if (!Value.Check(DocketSessionResultSchema, response.body)) {
          throw new ContractClientError(
            "RESPONSE_INVALID",
            "The response did not match its contract.",
          );
        }
        return response.body;
      }
      if (!Value.Check(StableErrorEnvelopeSchema, response.body)) {
        throw new ContractClientError(
          "RESPONSE_INVALID",
          "The error response did not match its contract.",
        );
      }
      const error = response.body;
      throw new ContractClientError(error.code, error.message, error.requestId);
    },

    async listDocketSessions(input: unknown): Promise<DocketSessionList> {
      if (!Value.Check(ListDocketSessionsRequestSchema, input)) {
        throw new ContractClientError(
          "REQUEST_INVALID",
          "The request is invalid.",
        );
      }
      const query = new URLSearchParams(input).toString();
      const response = await transport({
        method: "GET",
        path: "/v1/docket-sessions" + (query ? `?${query}` : ""),
      });
      if (response.status === 200) {
        if (!Value.Check(DocketSessionListSchema, response.body)) {
          throw new ContractClientError(
            "RESPONSE_INVALID",
            "The response did not match its contract.",
          );
        }
        return response.body;
      }
      if (!Value.Check(StableErrorEnvelopeSchema, response.body)) {
        throw new ContractClientError(
          "RESPONSE_INVALID",
          "The error response did not match its contract.",
        );
      }
      const error = response.body;
      throw new ContractClientError(error.code, error.message, error.requestId);
    },

    async revokeDocketSession(input: unknown): Promise<DocketSessionResult> {
      if (!Value.Check(RevokeDocketSessionRequestSchema, input)) {
        throw new ContractClientError(
          "REQUEST_INVALID",
          "The request is invalid.",
        );
      }
      const response = await transport({
        method: "POST",
        path: "/v1/docket-sessions/revoke",
        body: input,
      });
      if (response.status === 200) {
        if (!Value.Check(DocketSessionResultSchema, response.body)) {
          throw new ContractClientError(
            "RESPONSE_INVALID",
            "The response did not match its contract.",
          );
        }
        return response.body;
      }
      if (!Value.Check(StableErrorEnvelopeSchema, response.body)) {
        throw new ContractClientError(
          "RESPONSE_INVALID",
          "The error response did not match its contract.",
        );
      }
      const error = response.body;
      throw new ContractClientError(error.code, error.message, error.requestId);
    },

    async revokeAllDocketSessions(
      input: unknown,
    ): Promise<DocketSessionResult> {
      if (!Value.Check(RevokeAllDocketSessionsRequestSchema, input)) {
        throw new ContractClientError(
          "REQUEST_INVALID",
          "The request is invalid.",
        );
      }
      const response = await transport({
        method: "POST",
        path: "/v1/docket-sessions/revoke-all",
        body: input,
      });
      if (response.status === 200) {
        if (!Value.Check(DocketSessionResultSchema, response.body)) {
          throw new ContractClientError(
            "RESPONSE_INVALID",
            "The response did not match its contract.",
          );
        }
        return response.body;
      }
      if (!Value.Check(StableErrorEnvelopeSchema, response.body)) {
        throw new ContractClientError(
          "RESPONSE_INVALID",
          "The error response did not match its contract.",
        );
      }
      const error = response.body;
      throw new ContractClientError(error.code, error.message, error.requestId);
    },

    async listAccountSecurityHistory(
      input: unknown,
    ): Promise<AccountSecurityHistoryList> {
      if (!Value.Check(AccountSecurityHistoryRequestSchema, input)) {
        throw new ContractClientError(
          "REQUEST_INVALID",
          "The request is invalid.",
        );
      }
      const query = new URLSearchParams(input).toString();
      const response = await transport({
        method: "GET",
        path: "/v1/account/security-history" + (query ? `?${query}` : ""),
      });
      if (response.status === 200) {
        if (!Value.Check(AccountSecurityHistoryListSchema, response.body)) {
          throw new ContractClientError(
            "RESPONSE_INVALID",
            "The response did not match its contract.",
          );
        }
        return response.body;
      }
      if (!Value.Check(StableErrorEnvelopeSchema, response.body)) {
        throw new ContractClientError(
          "RESPONSE_INVALID",
          "The error response did not match its contract.",
        );
      }
      const error = response.body;
      throw new ContractClientError(error.code, error.message, error.requestId);
    },

    async getAccountProfile(input: unknown): Promise<AccountProfileProjection> {
      if (!Value.Check(AccountProfileRequestSchema, input)) {
        throw new ContractClientError(
          "REQUEST_INVALID",
          "The request is invalid.",
        );
      }
      const query = new URLSearchParams(input).toString();
      const response = await transport({
        method: "GET",
        path: "/v1/account/profile" + (query ? `?${query}` : ""),
      });
      if (response.status === 200) {
        if (!Value.Check(AccountProfileProjectionSchema, response.body)) {
          throw new ContractClientError(
            "RESPONSE_INVALID",
            "The response did not match its contract.",
          );
        }
        return response.body;
      }
      if (!Value.Check(StableErrorEnvelopeSchema, response.body)) {
        throw new ContractClientError(
          "RESPONSE_INVALID",
          "The error response did not match its contract.",
        );
      }
      const error = response.body;
      throw new ContractClientError(error.code, error.message, error.requestId);
    },

    async changeDisplayName(input: unknown): Promise<DocketSessionResult> {
      if (!Value.Check(ChangeDisplayNameRequestSchema, input)) {
        throw new ContractClientError(
          "REQUEST_INVALID",
          "The request is invalid.",
        );
      }
      const response = await transport({
        method: "POST",
        path: "/v1/account/display-name",
        body: input,
      });
      if (response.status === 200) {
        if (!Value.Check(DocketSessionResultSchema, response.body)) {
          throw new ContractClientError(
            "RESPONSE_INVALID",
            "The response did not match its contract.",
          );
        }
        return response.body;
      }
      if (!Value.Check(StableErrorEnvelopeSchema, response.body)) {
        throw new ContractClientError(
          "RESPONSE_INVALID",
          "The error response did not match its contract.",
        );
      }
      const error = response.body;
      throw new ContractClientError(error.code, error.message, error.requestId);
    },
  };
}
