// Generated by tools/contracts/generator.mjs. Do not edit.
import { Type, type Static } from "@sinclair/typebox";
import { Value } from "@sinclair/typebox/value";

export const IdentitySessionProjectionSchema = Type.Object(
  {
    audience: Type.Literal("self"),
    authenticated: Type.Literal(true),
    userId: Type.String({ maxLength: 128, minLength: 1 }),
  },
  { $id: "IdentitySessionProjection.v1", additionalProperties: false },
);
export type IdentitySessionProjection = Static<
  typeof IdentitySessionProjectionSchema
>;

export const IdentitySessionRequestSchema = Type.Object(
  { audience: Type.Literal("self") },
  { $id: "IdentitySessionRequest.v1", additionalProperties: false },
);
export type IdentitySessionRequest = Static<
  typeof IdentitySessionRequestSchema
>;

export const StableErrorEnvelopeSchema = Type.Object(
  {
    code: Type.Union([
      Type.Literal("AUTHENTICATION_REQUIRED"),
      Type.Literal("AUTHORITY_STALE"),
      Type.Literal("REQUEST_INVALID"),
      Type.Literal("RESPONSE_INVALID"),
    ]),
    fieldIssues: Type.Optional(
      Type.Array(
        Type.Object(
          { message: Type.String(), path: Type.String() },
          { additionalProperties: false },
        ),
      ),
    ),
    message: Type.String({ minLength: 1 }),
    requestId: Type.String({ maxLength: 128, minLength: 1 }),
  },
  { $id: "StableErrorEnvelope.v1", additionalProperties: false },
);
export type StableErrorEnvelope = Static<typeof StableErrorEnvelopeSchema>;

export interface ContractTransportResponse {
  readonly status: number;
  readonly body: unknown;
}
export type ContractTransport = (
  request: Readonly<{ method: string; path: string }>,
) => Promise<ContractTransportResponse>;

export class ContractClientError extends Error {
  constructor(
    public readonly code: string,
    message: string,
    public readonly requestId?: string,
  ) {
    super(message);
    this.name = "ContractClientError";
  }
}

export function createDocketClient(transport: ContractTransport) {
  return {
    async getIdentitySession(
      input: unknown,
    ): Promise<IdentitySessionProjection> {
      if (!Value.Check(IdentitySessionRequestSchema, input)) {
        throw new ContractClientError(
          "REQUEST_INVALID",
          "The request is invalid.",
        );
      }
      const query = new URLSearchParams(input).toString();
      const response = await transport({
        method: "GET",
        path: "/v1/session" + (query ? `?${query}` : ""),
      });
      if (response.status === 200) {
        if (!Value.Check(IdentitySessionProjectionSchema, response.body)) {
          throw new ContractClientError(
            "RESPONSE_INVALID",
            "The response did not match its contract.",
          );
        }
        return response.body;
      }
      if (!Value.Check(StableErrorEnvelopeSchema, response.body)) {
        throw new ContractClientError(
          "RESPONSE_INVALID",
          "The error response did not match its contract.",
        );
      }
      const error = response.body;
      throw new ContractClientError(error.code, error.message, error.requestId);
    },
  };
}
